# Generated by Django 4.2.9 on 2024-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_centered', models.TextField()),
                ('image_loading', models.TextField()),
                ('image_tile', models.TextField()),
                ('chance', models.DecimalField(decimal_places=3, max_digits=5)),
                ('hp', models.FloatField(default=0.0)),
                ('hpperlevel', models.FloatField(default=0.0)),
                ('mp', models.FloatField(default=0.0)),
                ('mpperlevel', models.FloatField(default=0.0)),
                ('movespeed', models.FloatField(default=0.0)),
                ('armor', models.FloatField(default=0.0)),
                ('armorperlevel', models.FloatField(default=0.0)),
                ('spellblock', models.FloatField(default=0.0)),
                ('spellblockperlevel', models.FloatField(default=0.0)),
                ('attackrange', models.FloatField(default=0.0)),
                ('hpregen', models.FloatField(default=0.0)),
                ('hpregenperlevel', models.FloatField(default=0.0)),
                ('mpregen', models.FloatField(default=0.0)),
                ('mpregenperlevel', models.FloatField(default=0.0)),
                ('crit', models.FloatField(default=0.0)),
                ('critperlevel', models.FloatField(default=0.0)),
                ('attackdamage', models.FloatField(default=0.0)),
                ('attackdamageperlevel', models.FloatField(default=0.0)),
                ('attackspeedperlevel', models.FloatField(default=0.0)),
                ('attackspeed', models.FloatField(default=0.0)),
                ('imasdf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('stats', models.JSONField(null=True)),
                ('chance', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
