# Generated by Django 4.2.9 on 2024-01-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='blurb',
        ),
    ]
