# Generated by Django 4.2.9 on 2024-01-29 13:59

from django.db import migrations, models
import gacha_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0003_remove_character_imasdf_remove_item_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(validators=[gacha_main.models.validate_clean]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120, validators=[gacha_main.models.validate_clean]),
        ),
    ]
