# Generated by Django 4.2.9 on 2024-02-07 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0005_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
