# Generated by Django 4.2.9 on 2024-02-25 18:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0006_character_skins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='value',
            new_name='total_value',
        ),
        migrations.AddField(
            model_name='item',
            name='from_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='item',
            name='into_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
