# Generated by Django 4.2.9 on 2024-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0007_rename_value_item_total_value_item_from_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='riot_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
