# Generated by Django 4.2.9 on 2024-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='player',
            name='items',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='custom_field',
            field=models.BooleanField(default=False),
        ),
    ]
