# Generated by Django 4.2.9 on 2024-01-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_delete_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
