# Generated by Django 4.2.9 on 2024-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_delete_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='characters',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.TextField(blank=True),
        ),
    ]
