# Generated by Django 4.2.9 on 2024-01-31 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_remove_profile_characters_remove_profile_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_team',
            field=models.CharField(blank=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('character_1', models.JSONField()),
                ('character_2', models.JSONField()),
                ('character_3', models.JSONField()),
                ('character_4', models.JSONField()),
                ('character_5', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(to='users.team'),
        ),
    ]
