# Generated by Django 4.2.9 on 2024-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0005_alter_item_description_alter_item_name'),
        ('users', '0011_profile_active_team_team_profile_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='characters',
            field=models.ManyToManyField(blank=True, to='gacha_main.character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(blank=True, to='gacha_main.item'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, to='users.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_1',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_2',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_3',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_4',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_5',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
