# Generated by Django 4.2.9 on 2024-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_team',
            field=models.IntegerField(blank=True),
        ),
    ]
