# Generated by Django 4.2.9 on 2024-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_active_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
