# Generated by Django 4.2.9 on 2024-02-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0005_alter_item_description_alter_item_name'),
        ('users', '0016_alter_profile_active_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_team',
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TeamCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gacha_main.character')),
                ('items', models.ManyToManyField(blank=True, to='gacha_main.item')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='character_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_1', to='users.teamcharacter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_2', to='users.teamcharacter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_3', to='users.teamcharacter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_4', to='users.teamcharacter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='character_5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_5', to='users.teamcharacter'),
        ),
    ]
