# Generated by Django 4.2.9 on 2024-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_active_team_team_active_teamcharacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcharacter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
