# Generated by Django 4.2.9 on 2024-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_teamcharacter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='character_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='character_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='character_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='character_4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='character_5',
        ),
        migrations.AddField(
            model_name='team',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='users.teamcharacter'),
        ),
    ]
