# Generated by Django 4.2.9 on 2024-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_team_character_1_remove_team_character_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='characters',
            field=models.ManyToManyField(blank=True, to='users.teamcharacter'),
        ),
    ]
