# Generated by Django 4.2.9 on 2024-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_avatar_alter_team_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blue_essence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='orange_essence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
