# Generated by Django 4.2.9 on 2024-02-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_main', '0005_alter_item_description_alter_item_name'),
        ('users', '0021_profile_blue_essence_profile_orange_essence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha_main.character'),
        ),
    ]
