# Generated by Django 4.2.9 on 2024-02-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_teamcharacter_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_character_basic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_character_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_character_premium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_item_basic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_item_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_item_premium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
